# Generated by Django 3.2.9 on 2022-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='dostavka/images', verbose_name='Изображение')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=40)),
            ],
        ),
    ]
