# Generated by Django 3.2.9 on 2022-04-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirotehnika_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostavka',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
    ]
