# Generated by Django 3.2.9 on 2022-04-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirotehnika_app', '0003_category_product'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
