# Generated by Django 3.2.9 on 2022-04-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirotehnika_app', '0005_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_photo',
            field=models.ImageField(upload_to='categories/images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='product/images', verbose_name='Фото'),
        ),
    ]
