# Generated by Django 3.2.9 on 2022-04-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirotehnika_app', '0008_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
