# Generated by Django 3.2.9 on 2022-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirotehnika_app', '0013_alter_categoryproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cats/'),
        ),
        migrations.AlterField(
            model_name='categoryproducts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
